### ISSUE TITLE
Not doing anything on reconnect on iOS?

### ISSUE THREAD

**Issue by joasag** [rodrigobastosv/connectivity_alert_widget#1]
Hi,

On Android this works great, and your example works great. But when using it on iOS, it only detects when I put the device in airplane mode that it is offline. Once I reconnect it wont update and show it is connected to the internet. This only happens on iOS.

I have the exact same issue with https://pub.dev/packages/flutter_offline

Any idea how to solve this?
I need to continously check the internet connection on my app.

**Comment by rodrigobastosv** [comment]
Hi @jockebq , i was travelling so i'm just seeing this now, Thanks for opening an issue!

TBH i don't garantee it will work on iOS, i don't have a mac nor iphone so i test my packages only for android. But i'm pretty sure it should work on iOS too.

The package has a dependency [connectivity](https://pub.dev/packages/connectivity) package. Try to follow the steps given in their README and please update me if it worked well or not.

In the meantime i'll try to update my README with specific info to setup foi iOS.

Thanks very much!

**Comment by joasag** [comment]
@rodrigobastosv no worries. I have the connectivity package as a dependency and also imported into the project. I have followed their readme, and from what I understand I only need to add `NSLocationAlwaysAndWhenInUseUsageDescription` and `NSLocationWhenInUseUsageDescription` to `<project root>/ios/Runner/Info.plist` which I have done.

**Comment by rodrigobastosv** [comment]
Hi @jockebq are you able to use the Connectivity package normally on iOS? What version of the [connectivity](https://pub.dev/packages/connectivity#-readme-tab-) are you using? If it's working correct i can update the version of this package on my own

**Comment by rodrigobastosv** [comment]
I just updated the dependencies on the new release of this plugin. Maybe you can update on your project to see if it works

**Comment by joasag** [comment]
@rodrigobastosv now the example works great on iOS. Thank you!
However I am having trouble using your plugin for the purpose I need it. I am replacing flutter_offline which I cannot make work on iOS. But this is the current code I am using with flutter_offline (works with Android).
Can I do the same with your plugin? Specifically `if connected == true`?

```
    return new Scaffold(
      body: OfflineBuilder(
        connectivityBuilder: (
            BuildContext context,
            ConnectivityResult connectivity,
            Widget child,
            ) {

          final bool connected = connectivity != ConnectivityResult.none;

          if (connected == true) { // Show link-page or URL from database
            fwp.reloadUrl(urlToLoad);
          }
          else { // Offline 404
            fwp.reloadUrl(localurloffline);
          }
          // Loading dots
          return WebviewScaffold(
            url: localurlloading,
            withJavascript: true,
            useWideViewPort: false,
            withZoom: false,
            scrollBar: false
          );

        },
        child: Column(
        ),
      ),
    );
```

**Comment by rodrigobastosv** [comment]
Hi @jockebq, thanks for your feedback.

You can't do that with this plugin right now. But i can see this as a great feature.

Give me a couple of days and i'll implement this

Thanks for using connectivity_alert_widget :)

**Comment by joasag** [comment]
That sounds fantastic, looking forward to testing it!

**Comment by rodrigobastosv** [comment]
Hi again @jockebq , the 1.0.1 version released today exposes a callback to be executed on every connectivity change.

I believe that this should serve you good.

Thanks again for using this package

**Comment by joasag** [comment]
@rodrigobastosv Great news! How do I implement this? I want to do the `if (connected == true)` and `false`, does it support this?

**Comment by rodrigobastosv** [comment]
Hi @jockebq, sorry for the delay. Didn't notice your answer.

You can check on the example. On onConnectivityResult gives you the connectivity result. Inside this callback you can do your logic like checking if its connected to do what you need

```
onConnectivityResult: (connectivity) => print(connectivity),
```
