### ISSUE TITLE
Se o app já iniciar sem internet não funciona.

### ISSUE THREAD

**Issue by AlexPassos** [rodrigobastosv/connectivity_alert_widget#2]
Olá, Parabéns pelo trabalho.

Esta acontecendo um bug.... se o app já iniciar sem internet não exibi a mensagem de offline.

**Comment by rodrigobastosv** [comment]
Olá @AlexPassos , obrigado por usar o package!

Vou analisar isso hoje mais tarde.

**Comment by rodrigobastosv** [comment]
Fiz vários testes e funcionou perfeitamente. Este package utiliza o package connectivity para fazer a checagem do status da internet. Podem ocorrer alguns falsos positivos, ou seja, você está com rede, mas não conectado a internet. Neste caso o connectivity retorna que você tem conectividade (pq de fato você tem).

Um teste que você pode fazer fácil é colocar o mobile ou emulador no modo avião e entrar no app. Deve com certeza ficar offline.

Me avisa qualquer coisa.

E novamente obrigado por utilizar o package

**Comment by AlexPassos** [comment]
Foi justamente isso que estava fazendo... coloquei o emulador  em modo avião. Só que não testei no aparelho.
Vou testar direto no aparelho e te falo.
